[package]
name = "vpn-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.38", features = ["full"] }
ratatui = "0.25.0"
crossterm = "0.27"
clap = { version = "4.5", features = ["derive"] }
rustls = "0.21"
webpki-roots = "0.22.6"
x509-parser = "0.16"
tun = "0.6"
anyhow = "1.0"
log = "0.4.27"
env_logger = "0.11.8"
tokio-rustls = "0.24"
rustls-pemfile = "1.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["iphlpapi"] }

[dev-dependencies]
tokio-test = "0.4.4"
